trigger:
  branches:
    include:
    - main
parameters:
- name: publishNuGetPackages
  displayName: Publish NuGet packages
  type: boolean
  default: false
- name: createGitHubRelease
  displayName: Create GitHub release
  type: boolean
  default: false
pool:
  vmImage: 'windows-latest'
variables:
- name: solution
  value: '**/*.slnx'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: codeCoverageEngine
  value: Cobertura
stages:
- stage: Initialize
  displayName: "Stage 'Initialize'"
  jobs:
  - job: JobInit1
    displayName: "Job Init (1) this"
    steps:
    - task: CmdLine@2
      displayName: "Init 'that'"
      inputs:
        script: echo "Running init in Job Init2"
    - task: UseDotNet@2
      displayName: "🔰 Ensure .NET 10 SDK"
      inputs:
        packageType: 'sdk'
        version: '10.0.301'
        includePreview: false
    - task: CmdLine@2
      displayName: 'Verify dotnet/sdk'
      inputs:
        script: |
          dotnet --version
          dotnet --list-sdks
          dotnet --info
    - task: DotNetCoreCLI@2
      displayName: "🤓 Install NBGV"
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path $(Agent.TempDirectory) nbgv
    - task: CmdLine@2
      displayName: "✌️ Initialize NBGV"
      inputs:
        script: $(Agent.TempDirectory)/nbgv cloud --common-vars --all-vars
    - task: CmdLine@2
      displayName: 'Run a multiline script'
      inputs:
        script: >
          echo Add publishNuGetPackages:False...

          echo See buildPlatform:$(buildPlatform), buildConfiguration:$(buildConfiguration)...
    - task: NuGetToolInstaller@1
    - task: DotNetCoreCLI@2
      displayName: 'dotnet: restore solution'
      inputs:
        command: 'restore'
        projects: '$(solution)'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet: build solution'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet: test'
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) --no-build --verbosity normal'
    - task: NuGetCommand@2
      displayName: 'Nuget : do nothing (default restore)'
      condition: and(succeeded(), eq(False, true))
    - task: DotNetCoreCLI@2
      displayName: "📦 Pack StoreLake (Release)"
      inputs:
        command: custom
        projects: src/StoreLake
        custom: pack
        arguments: >
          --configuration Release --output $(Build.ArtifactStagingDirectory)/packages --force
    - task: DotNetCoreCLI@2
      displayName: "📦 Pack StoreLake.Sdk (Release)"
      inputs:
        command: custom
        projects: src/StoreLake.Sdk
        custom: pack
        arguments: >
          --configuration Release --output $(Build.ArtifactStagingDirectory)/packages --force
    - task: DotNetCoreCLI@2
      displayName: "📦 Pack StoreLake.Sdk.Cli (Release)"
      inputs:
        command: custom
        projects: src/StoreLake.Sdk.Cli
        custom: pack
        arguments: >
          --configuration Release --output $(Build.ArtifactStagingDirectory)/packages --force
    - task: PowerShell@2
      displayName: "👮 Ensure artifact folder 'packages' exists"
      inputs:
        targetType: inline
        script: New-Item -ItemType Directory -Force -Path $(Build.ArtifactStagingDirectory)/packages
        pwsh: true
    - task: ecdc45f6-832d-4ad9-b52b-ee49e94659be@1
      displayName: "💾 Publish 'NuGet packages' artifact"
      inputs:
        path: $(Build.ArtifactStagingDirectory)/packages
        artifactName: NuGet packages
    - task: CmdLine@2
      displayName: "Nuget : push-skipped"
      condition: and(succeeded(), eq(False, false))
      inputs:
        script: echo "skip nuget push due to parameter value"
    - task: NuGetCommand@2
      displayName: 'Nuget : push'
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
        verbosityPush: 'Detailed'
      condition: and(succeeded(), eq(False, true))
    - task: GitHubRelease@1
      displayName: ?? Create GitHub release
      inputs:
        gitHubConnection: 'benhauman'
        repositoryName: $(Build.Repository.Name)
        target: $(Build.SourceVersion)
        tagSource: userSpecifiedTag
        tag: 'v$(Build.BuildNumber)'
        title: 'v$(Build.BuildNumber)'
        assets: |
          $(Pipeline.Workspace)/CI/NuGet packages/*.nupkg
          $(Pipeline.Workspace)/CI/Publish output*/*.zip
        changeLogCompareToRelease: lastFullRelease
        changeLogCompareToReleaseTag: v$(NBGV_MAJORMINORVERSION)\.\d+$
        changeLogType: commitBased
      condition: and(succeeded(), eq(False, true))
