<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <EnableParallelization>true</EnableParallelization>
    <NoWarn>$(NoWarn);8981;MSTEST0001</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Skrypton\Skrypton.csproj" />

    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="19.14.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />

    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="VbsResources\**\*.cs" />
    <None Include="VbsResources\**\*.cs" />
    <EmbeddedResource Include="VbsResources\**\*.sql" />
    <EmbeddedResource Include="VbsResources\**\*.vbs" />
    <EmbeddedResource Include="VbsResources\**\*.xml" />
    <EmbeddedResource Include="VbsResources\**\*.cs" />
    <EmbeddedResource Include="VbsResources\**\*.cstxt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Skrypton\" />
  </ItemGroup>

</Project>
